### ISSUE TITLE
Crawled (403) <GET https://pixabay.com/> (referer: https://pixabay.com/photos/)

### ISSUE THREAD

**Issue by lyc0221** [Jihun0109/pixabay-downloader#1]
how to resolve ?

> 2020-07-22 07:45:32 [scrapy] INFO: Scrapy 1.0.3 started (bot: pixabay)
2020-07-22 07:45:32 [scrapy] INFO: Optional features available: ssl, http11, boto
2020-07-22 07:45:32 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'pixabay.spiders', 'SPIDER_MODULES': ['pixabay.spiders'], 'USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36', 'BOT_NAME': 'pixabay'}
2020-07-22 07:45:33 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2020-07-22 07:45:33 [boto] DEBUG: Retrieving credentials from metadata server.
2020-07-22 07:45:33 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
2020-07-22 07:45:33 [boto] ERROR: Unable to read instance data, giving up
2020-07-22 07:45:33 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2020-07-22 07:45:33 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2020-07-22 07:45:33 [scrapy] INFO: Enabled item pipelines:
2020-07-22 07:45:33 [scrapy] INFO: Spider opened
2020-07-22 07:45:33 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-07-22 07:45:33 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2020-07-22 07:45:33 [scrapy] DEBUG: Crawled (403) <GET https://pixabay.com/> (referer: https://pixabay.com/photos/)
2020-07-22 07:45:33 [scrapy] DEBUG: Ignoring response <403 https://pixabay.com/>: HTTP status code is not handled or not allowed
2020-07-22 07:45:33 [scrapy] INFO: Closing spider (finished)
2020-07-22 07:45:33 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 224,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 5030,
 'downloader/response_count': 1,
 'downloader/response_status_count/403': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 7, 22, 7, 45, 33, 432103),
 'log_count/DEBUG': 4,
 'log_count/ERROR': 2,
 'log_count/INFO': 7,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 7, 22, 7, 45, 33, 135709)}
2020-07-22 07:45:33 [scrapy] INFO: Spider closed (finished)

**Comment by burlibu** [comment]
Hello. How do I use this functionality to download from pixabay? Is it a chrome extension?
